// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_mirror::schema::lib::Input as OrdinaryInput;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::Output as OrdinaryOutput;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::AppendReceipt as AppendReceipt;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::AppendRejection as AppendRejection;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::CheckpointArtifact as CheckpointArtifact;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::CheckpointReceipt as CheckpointReceipt;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::ObjectNoticeReceipt as ObjectNoticeReceipt;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::ObjectNoticeRejection as ObjectNoticeRejection;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::PublishRejection as PublishRejection;
#[rustfmt::skip]
pub use crate::schema::sema::WriteInput as SemaWriteInput;
#[rustfmt::skip]
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadOutput as SemaReadOutput;
#[rustfmt::skip]
pub use crate::schema::sema::NovelSuffix as NovelSuffix;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalArrived(OrdinaryInput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaWriteCompleted(SemaWriteOutput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadCompleted(SemaReadOutput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReplyToSignal(OrdinaryOutput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaWrite(SemaWriteInput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaRead(SemaReadInput);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Continue(NexusWork);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    Continue(Continue),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AppendDecision {
    AcceptSuffix(NovelSuffix),
    AcknowledgeDuplicate(AppendReceipt),
    RefuseAppend(AppendRejection),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CheckpointDecision {
    AcceptCheckpoint(CheckpointArtifact),
    AcknowledgeCheckpoint(CheckpointReceipt),
    RefuseCheckpoint(PublishRejection),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ObjectNoticeDecision {
    AcceptObjectNotice(ObjectNoticeReceipt),
    RefuseObjectNotice(ObjectNoticeRejection),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    Continue(Continue),
}

#[rustfmt::skip]
impl SignalArrived {
    pub fn new(payload: OrdinaryInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OrdinaryInput {
        &self.0
    }
    pub fn into_payload(self) -> OrdinaryInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<OrdinaryInput> for SignalArrived {
    fn from(payload: OrdinaryInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteCompleted {
    pub fn new(payload: SemaWriteOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteOutput> for SemaWriteCompleted {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadCompleted {
    pub fn new(payload: SemaReadOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadOutput> for SemaReadCompleted {
    fn from(payload: SemaReadOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReplyToSignal {
    pub fn new(payload: OrdinaryOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OrdinaryOutput {
        &self.0
    }
    pub fn into_payload(self) -> OrdinaryOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<OrdinaryOutput> for ReplyToSignal {
    fn from(payload: OrdinaryOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaWrite {
    pub fn new(payload: SemaWriteInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteInput> for CommandSemaWrite {
    fn from(payload: SemaWriteInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaRead {
    pub fn new(payload: SemaReadInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadInput> for CommandSemaRead {
    fn from(payload: SemaReadInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Continue {
    pub fn new(payload: NexusWork) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusWork {
        &self.0
    }
    pub fn into_payload(self) -> NexusWork {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusWork> for Continue {
    fn from(payload: NexusWork) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: OrdinaryInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn reply_to_signal(payload: OrdinaryOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl AppendDecision {
    pub fn accept_suffix(payload: NovelSuffix) -> Self {
        Self::AcceptSuffix(payload)
    }
    pub fn acknowledge_duplicate(payload: AppendReceipt) -> Self {
        Self::AcknowledgeDuplicate(payload)
    }
    pub fn refuse_append(payload: AppendRejection) -> Self {
        Self::RefuseAppend(payload)
    }
}

#[rustfmt::skip]
impl CheckpointDecision {
    pub fn accept_checkpoint(payload: CheckpointArtifact) -> Self {
        Self::AcceptCheckpoint(payload)
    }
    pub fn acknowledge_checkpoint(payload: CheckpointReceipt) -> Self {
        Self::AcknowledgeCheckpoint(payload)
    }
    pub fn refuse_checkpoint(payload: PublishRejection) -> Self {
        Self::RefuseCheckpoint(payload)
    }
}

#[rustfmt::skip]
impl ObjectNoticeDecision {
    pub fn accept_object_notice(payload: ObjectNoticeReceipt) -> Self {
        Self::AcceptObjectNotice(payload)
    }
    pub fn refuse_object_notice(payload: ObjectNoticeRejection) -> Self {
        Self::RefuseObjectNotice(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: OrdinaryInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn reply_to_signal(payload: OrdinaryOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for NexusWork {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for NexusWork {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for NexusWork {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for NexusAction {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for NexusAction {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for NexusAction {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for NexusAction {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<NovelSuffix> for AppendDecision {
    fn from(payload: NovelSuffix) -> Self {
        Self::AcceptSuffix(payload)
    }
}

#[rustfmt::skip]
impl From<AppendReceipt> for AppendDecision {
    fn from(payload: AppendReceipt) -> Self {
        Self::AcknowledgeDuplicate(payload)
    }
}

#[rustfmt::skip]
impl From<AppendRejection> for AppendDecision {
    fn from(payload: AppendRejection) -> Self {
        Self::RefuseAppend(payload)
    }
}

#[rustfmt::skip]
impl From<CheckpointArtifact> for CheckpointDecision {
    fn from(payload: CheckpointArtifact) -> Self {
        Self::AcceptCheckpoint(payload)
    }
}

#[rustfmt::skip]
impl From<CheckpointReceipt> for CheckpointDecision {
    fn from(payload: CheckpointReceipt) -> Self {
        Self::AcknowledgeCheckpoint(payload)
    }
}

#[rustfmt::skip]
impl From<PublishRejection> for CheckpointDecision {
    fn from(payload: PublishRejection) -> Self {
        Self::RefuseCheckpoint(payload)
    }
}

#[rustfmt::skip]
impl From<ObjectNoticeReceipt> for ObjectNoticeDecision {
    fn from(payload: ObjectNoticeReceipt) -> Self {
        Self::AcceptObjectNotice(payload)
    }
}

#[rustfmt::skip]
impl From<ObjectNoticeRejection> for ObjectNoticeDecision {
    fn from(payload: ObjectNoticeRejection) -> Self {
        Self::RefuseObjectNotice(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for Input {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for Input {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for Input {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for Output {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for Output {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for Output {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for Output {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_ {
        async move {
            self.trace_nexus_entered();
            let output = self.decide(input);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
