// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
)]
pub struct Bytes(nota::ByteSequence);
#[rustfmt::skip]
impl Bytes {
    pub fn new(payload: Vec<u8>) -> Self {
        Self(nota::ByteSequence::new(payload))
    }
    pub fn payload(&self) -> &[u8] {
        self.0.payload()
    }
    pub fn into_payload(self) -> Vec<u8> {
        self.0.into_payload()
    }
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
)]
pub struct FixedBytes<const WIDTH: usize>(nota::FixedByteSequence<WIDTH>);
#[rustfmt::skip]
impl<const WIDTH: usize> FixedBytes<WIDTH> {
    pub fn new(payload: [u8; WIDTH]) -> Self {
        Self(nota::FixedByteSequence::new(payload))
    }
    pub fn payload(&self) -> &[u8; WIDTH] {
        self.0.payload()
    }
    pub fn into_payload(self) -> [u8; WIDTH] {
        self.0.into_payload()
    }
}

#[rustfmt::skip]
pub use signal_mirror::schema::lib::StoreName as StoreName;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::CommitSequence as CommitSequence;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::EntryDigest as EntryDigest;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::HeadMark as HeadMark;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::EntryEnvelope as EntryEnvelope;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::EntrySuffix as EntrySuffix;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::CheckpointArtifact as CheckpointArtifact;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::AppendReceipt as AppendReceipt;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::CheckpointReceipt as CheckpointReceipt;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::ObjectNotice as ObjectNotice;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::ObjectNoticeReceipt as ObjectNoticeReceipt;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::ObjectNoticeRejection as ObjectNoticeRejection;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::RestoreQuery as RestoreQuery;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::RestoreBundle as RestoreBundle;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::RestoreRejection as RestoreRejection;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::HeadQuery as HeadQuery;
#[rustfmt::skip]
pub use signal_mirror::schema::lib::HeadListing as HeadListing;
#[rustfmt::skip]
pub use meta_signal_mirror::schema::lib::StoreRegistration as StoreRegistration;
#[rustfmt::skip]
pub use meta_signal_mirror::schema::lib::RegistrationReceipt as RegistrationReceipt;
#[rustfmt::skip]
pub use meta_signal_mirror::schema::lib::StoreRetirement as StoreRetirement;
#[rustfmt::skip]
pub use meta_signal_mirror::schema::lib::RetirementReceipt as RetirementReceipt;
#[rustfmt::skip]
pub use meta_signal_mirror::schema::lib::RetentionOrder as RetentionOrder;
#[rustfmt::skip]
pub use meta_signal_mirror::schema::lib::RetentionReceipt as RetentionReceipt;
#[rustfmt::skip]
pub use meta_signal_mirror::schema::lib::RegistryQuery as RegistryQuery;
#[rustfmt::skip]
pub use meta_signal_mirror::schema::lib::RegistryListing as RegistryListing;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteInput {
    PersistSuffix(NovelSuffix),
    PersistCheckpoint(CheckpointArtifact),
    RegisterStore(StoreRegistration),
    RetireStore(StoreRetirement),
    PersistRetention(RetentionOrder),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadInput {
    CheckAppend(EntrySuffix),
    CheckCheckpoint(CheckpointArtifact),
    CheckObjectNotice(ObjectNotice),
    LoadRestore(RestoreQuery),
    LoadHeads(HeadQuery),
    LoadRegistry(RegistryQuery),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteOutput {
    SuffixPersisted(AppendReceipt),
    CheckpointPersisted(CheckpointReceipt),
    StoreRegistered(RegistrationReceipt),
    StoreRetired(RetirementReceipt),
    RetentionPersisted(RetentionReceipt),
    WriteFaulted(LedgerFault),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadOutput {
    AppendChecked(CheckedAppend),
    CheckpointChecked(CheckedCheckpoint),
    ObjectNoticeChecked(CheckedObjectNotice),
    RestoreLoaded(RestoreBundle),
    RestoreRefused(RestoreRejection),
    HeadsLoaded(HeadListing),
    RegistryLoaded(RegistryListing),
    ReadFaulted(LedgerFault),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Entries(Vec<EntryEnvelope>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NovelSuffix {
    pub store: StoreName,
    pub head: HeadMark,
    pub(crate) entries: Entries,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KnownEntry {
    pub sequence: CommitSequence,
    pub digest: EntryDigest,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ContentAddressing {
    Opaque,
    SemaVersionedLog,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct LedgerHead(Option<HeadMark>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct KnownEntries(Vec<KnownEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct LatestCheckpoint(Option<CheckpointReceipt>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisteredLedger {
    pub(crate) ledger_head: LedgerHead,
    pub(crate) known_entries: KnownEntries,
    pub(crate) latest_checkpoint: LatestCheckpoint,
    pub addressing: ContentAddressing,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum StoreLedger {
    Registered(RegisteredLedger),
    Unregistered,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckedAppend {
    pub request: EntrySuffix,
    pub ledger: StoreLedger,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckedCheckpoint {
    pub artifact: CheckpointArtifact,
    pub ledger: StoreLedger,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckedObjectNotice {
    pub notice: ObjectNotice,
    pub ledger: StoreLedger,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LedgerFault(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DigestBytes(FixedBytes<32>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HeadStamp {
    pub sequence: Integer,
    pub digest: DigestBytes,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct StoredHeadStamp(Option<HeadStamp>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredHead {
    pub store: String,
    pub(crate) stored_head_stamp: StoredHeadStamp,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct PreviousDigest(Option<DigestBytes>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReceivedEntry {
    pub store: String,
    pub sequence: Integer,
    pub(crate) previous_digest: PreviousDigest,
    pub digest: DigestBytes,
    pub payload: Bytes,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredCheckpoint {
    pub store: String,
    pub sequence: Integer,
    pub covered_end: Integer,
    pub digest: DigestBytes,
    pub artifact: Bytes,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct KeepCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RetentionRule {
    KeepEverything,
    KeepLatestCheckpoints(KeepCount),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Scope(Option<String>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetentionSetting {
    pub(crate) scope: Scope,
    pub rule: RetentionRule,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StorePolicy {
    pub store: String,
    pub addressing: ContentAddressing,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    WriteInput(WriteInput),
    ReadInput(ReadInput),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    WriteOutput(WriteOutput),
    ReadOutput(ReadOutput),
}

#[rustfmt::skip]
impl Entries {
    pub fn new(payload: Vec<EntryEnvelope>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EntryEnvelope> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EntryEnvelope> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EntryEnvelope>> for Entries {
    fn from(payload: Vec<EntryEnvelope>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LedgerHead {
    pub fn new(payload: Option<HeadMark>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<HeadMark> {
        &self.0
    }
    pub fn into_payload(self) -> Option<HeadMark> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<HeadMark>> for LedgerHead {
    fn from(payload: Option<HeadMark>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl KnownEntries {
    pub fn new(payload: Vec<KnownEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<KnownEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<KnownEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<KnownEntry>> for KnownEntries {
    fn from(payload: Vec<KnownEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LatestCheckpoint {
    pub fn new(payload: Option<CheckpointReceipt>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<CheckpointReceipt> {
        &self.0
    }
    pub fn into_payload(self) -> Option<CheckpointReceipt> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<CheckpointReceipt>> for LatestCheckpoint {
    fn from(payload: Option<CheckpointReceipt>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LedgerFault {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for LedgerFault {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DigestBytes {
    pub fn new(payload: FixedBytes<32>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &FixedBytes<32> {
        &self.0
    }
    pub fn into_payload(self) -> FixedBytes<32> {
        self.0
    }
}
#[rustfmt::skip]
impl From<FixedBytes<32>> for DigestBytes {
    fn from(payload: FixedBytes<32>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StoredHeadStamp {
    pub fn new(payload: Option<HeadStamp>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<HeadStamp> {
        &self.0
    }
    pub fn into_payload(self) -> Option<HeadStamp> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<HeadStamp>> for StoredHeadStamp {
    fn from(payload: Option<HeadStamp>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PreviousDigest {
    pub fn new(payload: Option<DigestBytes>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<DigestBytes> {
        &self.0
    }
    pub fn into_payload(self) -> Option<DigestBytes> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<DigestBytes>> for PreviousDigest {
    fn from(payload: Option<DigestBytes>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl KeepCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for KeepCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Scope {
    pub fn new(payload: Option<String>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<String> {
        &self.0
    }
    pub fn into_payload(self) -> Option<String> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<String>> for Scope {
    fn from(payload: Option<String>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WriteInput {
    pub fn persist_suffix(payload: NovelSuffix) -> Self {
        Self::PersistSuffix(payload)
    }
    pub fn persist_checkpoint(payload: CheckpointArtifact) -> Self {
        Self::PersistCheckpoint(payload)
    }
    pub fn register_store(payload: StoreRegistration) -> Self {
        Self::RegisterStore(payload)
    }
    pub fn retire_store(payload: StoreRetirement) -> Self {
        Self::RetireStore(payload)
    }
    pub fn persist_retention(payload: RetentionOrder) -> Self {
        Self::PersistRetention(payload)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn check_append(payload: EntrySuffix) -> Self {
        Self::CheckAppend(payload)
    }
    pub fn check_checkpoint(payload: CheckpointArtifact) -> Self {
        Self::CheckCheckpoint(payload)
    }
    pub fn check_object_notice(payload: ObjectNotice) -> Self {
        Self::CheckObjectNotice(payload)
    }
    pub fn load_restore(payload: RestoreQuery) -> Self {
        Self::LoadRestore(payload)
    }
    pub fn load_heads(payload: HeadQuery) -> Self {
        Self::LoadHeads(payload)
    }
    pub fn load_registry(payload: RegistryQuery) -> Self {
        Self::LoadRegistry(payload)
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn suffix_persisted(payload: AppendReceipt) -> Self {
        Self::SuffixPersisted(payload)
    }
    pub fn checkpoint_persisted(payload: CheckpointReceipt) -> Self {
        Self::CheckpointPersisted(payload)
    }
    pub fn store_registered(payload: RegistrationReceipt) -> Self {
        Self::StoreRegistered(payload)
    }
    pub fn store_retired(payload: RetirementReceipt) -> Self {
        Self::StoreRetired(payload)
    }
    pub fn retention_persisted(payload: RetentionReceipt) -> Self {
        Self::RetentionPersisted(payload)
    }
    pub fn write_faulted(payload: String) -> Self {
        Self::WriteFaulted(LedgerFault::new(payload))
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn append_checked(payload: CheckedAppend) -> Self {
        Self::AppendChecked(payload)
    }
    pub fn checkpoint_checked(payload: CheckedCheckpoint) -> Self {
        Self::CheckpointChecked(payload)
    }
    pub fn object_notice_checked(payload: CheckedObjectNotice) -> Self {
        Self::ObjectNoticeChecked(payload)
    }
    pub fn restore_loaded(payload: RestoreBundle) -> Self {
        Self::RestoreLoaded(payload)
    }
    pub fn restore_refused(payload: RestoreRejection) -> Self {
        Self::RestoreRefused(payload)
    }
    pub fn heads_loaded(payload: HeadListing) -> Self {
        Self::HeadsLoaded(payload)
    }
    pub fn registry_loaded(payload: RegistryListing) -> Self {
        Self::RegistryLoaded(payload)
    }
    pub fn read_faulted(payload: String) -> Self {
        Self::ReadFaulted(LedgerFault::new(payload))
    }
}

#[rustfmt::skip]
impl StoreLedger {
    pub fn registered(payload: RegisteredLedger) -> Self {
        Self::Registered(payload)
    }
}

#[rustfmt::skip]
impl RetentionRule {
    pub fn keep_latest_checkpoints(payload: Integer) -> Self {
        Self::KeepLatestCheckpoints(KeepCount::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn write_input(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
    pub fn read_input(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn write_output(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
    pub fn read_output(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<NovelSuffix> for WriteInput {
    fn from(payload: NovelSuffix) -> Self {
        Self::PersistSuffix(payload)
    }
}

#[rustfmt::skip]
impl From<CheckpointArtifact> for WriteInput {
    fn from(payload: CheckpointArtifact) -> Self {
        Self::PersistCheckpoint(payload)
    }
}

#[rustfmt::skip]
impl From<StoreRegistration> for WriteInput {
    fn from(payload: StoreRegistration) -> Self {
        Self::RegisterStore(payload)
    }
}

#[rustfmt::skip]
impl From<StoreRetirement> for WriteInput {
    fn from(payload: StoreRetirement) -> Self {
        Self::RetireStore(payload)
    }
}

#[rustfmt::skip]
impl From<RetentionOrder> for WriteInput {
    fn from(payload: RetentionOrder) -> Self {
        Self::PersistRetention(payload)
    }
}

#[rustfmt::skip]
impl From<EntrySuffix> for ReadInput {
    fn from(payload: EntrySuffix) -> Self {
        Self::CheckAppend(payload)
    }
}

#[rustfmt::skip]
impl From<CheckpointArtifact> for ReadInput {
    fn from(payload: CheckpointArtifact) -> Self {
        Self::CheckCheckpoint(payload)
    }
}

#[rustfmt::skip]
impl From<ObjectNotice> for ReadInput {
    fn from(payload: ObjectNotice) -> Self {
        Self::CheckObjectNotice(payload)
    }
}

#[rustfmt::skip]
impl From<RestoreQuery> for ReadInput {
    fn from(payload: RestoreQuery) -> Self {
        Self::LoadRestore(payload)
    }
}

#[rustfmt::skip]
impl From<HeadQuery> for ReadInput {
    fn from(payload: HeadQuery) -> Self {
        Self::LoadHeads(payload)
    }
}

#[rustfmt::skip]
impl From<RegistryQuery> for ReadInput {
    fn from(payload: RegistryQuery) -> Self {
        Self::LoadRegistry(payload)
    }
}

#[rustfmt::skip]
impl From<AppendReceipt> for WriteOutput {
    fn from(payload: AppendReceipt) -> Self {
        Self::SuffixPersisted(payload)
    }
}

#[rustfmt::skip]
impl From<CheckpointReceipt> for WriteOutput {
    fn from(payload: CheckpointReceipt) -> Self {
        Self::CheckpointPersisted(payload)
    }
}

#[rustfmt::skip]
impl From<RegistrationReceipt> for WriteOutput {
    fn from(payload: RegistrationReceipt) -> Self {
        Self::StoreRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<RetirementReceipt> for WriteOutput {
    fn from(payload: RetirementReceipt) -> Self {
        Self::StoreRetired(payload)
    }
}

#[rustfmt::skip]
impl From<RetentionReceipt> for WriteOutput {
    fn from(payload: RetentionReceipt) -> Self {
        Self::RetentionPersisted(payload)
    }
}

#[rustfmt::skip]
impl From<LedgerFault> for WriteOutput {
    fn from(payload: LedgerFault) -> Self {
        Self::WriteFaulted(payload)
    }
}

#[rustfmt::skip]
impl From<CheckedAppend> for ReadOutput {
    fn from(payload: CheckedAppend) -> Self {
        Self::AppendChecked(payload)
    }
}

#[rustfmt::skip]
impl From<CheckedCheckpoint> for ReadOutput {
    fn from(payload: CheckedCheckpoint) -> Self {
        Self::CheckpointChecked(payload)
    }
}

#[rustfmt::skip]
impl From<CheckedObjectNotice> for ReadOutput {
    fn from(payload: CheckedObjectNotice) -> Self {
        Self::ObjectNoticeChecked(payload)
    }
}

#[rustfmt::skip]
impl From<RestoreBundle> for ReadOutput {
    fn from(payload: RestoreBundle) -> Self {
        Self::RestoreLoaded(payload)
    }
}

#[rustfmt::skip]
impl From<RestoreRejection> for ReadOutput {
    fn from(payload: RestoreRejection) -> Self {
        Self::RestoreRefused(payload)
    }
}

#[rustfmt::skip]
impl From<HeadListing> for ReadOutput {
    fn from(payload: HeadListing) -> Self {
        Self::HeadsLoaded(payload)
    }
}

#[rustfmt::skip]
impl From<RegistryListing> for ReadOutput {
    fn from(payload: RegistryListing) -> Self {
        Self::RegistryLoaded(payload)
    }
}

#[rustfmt::skip]
impl From<LedgerFault> for ReadOutput {
    fn from(payload: LedgerFault) -> Self {
        Self::ReadFaulted(payload)
    }
}

#[rustfmt::skip]
impl From<RegisteredLedger> for StoreLedger {
    fn from(payload: RegisteredLedger) -> Self {
        Self::Registered(payload)
    }
}

#[rustfmt::skip]
impl From<KeepCount> for RetentionRule {
    fn from(payload: KeepCount) -> Self {
        Self::KeepLatestCheckpoints(payload)
    }
}

#[rustfmt::skip]
impl From<WriteInput> for Input {
    fn from(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadInput> for Input {
    fn from(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<WriteOutput> for Output {
    fn from(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadOutput> for Output {
    fn from(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod family_identity {
    pub const HEAD_FAMILY: [u8; 32] = [
        223, 2, 224, 245, 104, 190, 236, 33, 145, 54, 141, 62, 213, 13, 194, 122, 136,
        13, 4, 225, 250, 89, 122, 196, 192, 153, 14, 160, 29, 146, 249, 236,
    ];
    pub const ENTRY_FAMILY: [u8; 32] = [
        203, 100, 4, 182, 49, 4, 76, 108, 242, 250, 208, 170, 96, 229, 253, 171, 12, 14,
        84, 35, 61, 212, 78, 103, 117, 54, 110, 230, 61, 199, 145, 61,
    ];
    pub const CHECKPOINT_FAMILY: [u8; 32] = [
        223, 206, 44, 190, 227, 139, 236, 38, 38, 192, 70, 175, 154, 170, 29, 47, 156,
        83, 8, 52, 161, 252, 123, 77, 56, 129, 201, 102, 115, 213, 8, 39,
    ];
    pub const RETENTION_FAMILY: [u8; 32] = [
        250, 110, 230, 190, 122, 28, 150, 34, 205, 102, 169, 254, 90, 143, 65, 117, 150,
        38, 67, 81, 98, 226, 212, 140, 157, 29, 30, 43, 71, 103, 24, 226,
    ];
    pub const POLICY_FAMILY: [u8; 32] = [
        50, 3, 227, 235, 58, 221, 188, 198, 75, 202, 70, 175, 84, 117, 40, 190, 186, 83,
        198, 222, 72, 144, 241, 163, 228, 59, 133, 20, 83, 203, 228, 101,
    ];
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RecordFamilyError {
    UnknownFamily { family: sema_engine::FamilyName },
    SchemaHashMismatch {
        family: sema_engine::FamilyName,
        stored: sema_engine::SchemaHash,
        generated: sema_engine::SchemaHash,
    },
    RecordDecode { family: sema_engine::FamilyName },
}
#[rustfmt::skip]
impl std::fmt::Display for RecordFamilyError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnknownFamily { family } => {
                write!(formatter, "unknown record family {family}")
            }
            Self::SchemaHashMismatch { family, stored, generated } => {
                write!(
                    formatter,
                    "schema hash mismatch for record family {family}: stored {stored}, generated {generated}",
                )
            }
            Self::RecordDecode { family } => {
                write!(formatter, "failed to decode {family} record archive")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for RecordFamilyError {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq)]
pub enum RecordFamily {
    HeadFamily(StoredHead),
    EntryFamily(ReceivedEntry),
    CheckpointFamily(StoredCheckpoint),
    RetentionFamily(RetentionSetting),
    PolicyFamily(StorePolicy),
}
#[rustfmt::skip]
impl RecordFamily {
    pub const STORE_NAME: &'static str = "mirror:sema";
    pub fn versioning_policy() -> sema_engine::VersioningPolicy {
        sema_engine::VersioningPolicy::new(
            sema_engine::VersionedStoreName::new(Self::STORE_NAME),
        )
    }
    pub fn head_family() -> sema_engine::TableDescriptor<StoredHead> {
        sema_engine::TableDescriptor::new(
            sema_engine::TableName::new("store-heads"),
            sema_engine::FamilyName::new("HeadFamily"),
            sema_engine::SchemaHash::new(family_identity::HEAD_FAMILY),
        )
    }
    pub fn entry_family() -> sema_engine::TableDescriptor<ReceivedEntry> {
        sema_engine::TableDescriptor::new(
            sema_engine::TableName::new("received-entries"),
            sema_engine::FamilyName::new("EntryFamily"),
            sema_engine::SchemaHash::new(family_identity::ENTRY_FAMILY),
        )
    }
    pub fn checkpoint_family() -> sema_engine::TableDescriptor<StoredCheckpoint> {
        sema_engine::TableDescriptor::new(
            sema_engine::TableName::new("checkpoint-artifacts"),
            sema_engine::FamilyName::new("CheckpointFamily"),
            sema_engine::SchemaHash::new(family_identity::CHECKPOINT_FAMILY),
        )
    }
    pub fn retention_family() -> sema_engine::TableDescriptor<RetentionSetting> {
        sema_engine::TableDescriptor::new(
            sema_engine::TableName::new("retention-rules"),
            sema_engine::FamilyName::new("RetentionFamily"),
            sema_engine::SchemaHash::new(family_identity::RETENTION_FAMILY),
        )
    }
    pub fn policy_family() -> sema_engine::TableDescriptor<StorePolicy> {
        sema_engine::TableDescriptor::new(
            sema_engine::TableName::new("store-policies"),
            sema_engine::FamilyName::new("PolicyFamily"),
            sema_engine::SchemaHash::new(family_identity::POLICY_FAMILY),
        )
    }
    pub fn decode(
        identity: &sema_engine::FamilyIdentity,
        bytes: &[u8],
    ) -> Result<Self, RecordFamilyError> {
        match identity.family().as_str() {
            "HeadFamily" => {
                let generated = sema_engine::SchemaHash::new(
                    family_identity::HEAD_FAMILY,
                );
                if identity.schema_hash() != generated {
                    return Err(RecordFamilyError::SchemaHashMismatch {
                        family: sema_engine::FamilyName::new("HeadFamily"),
                        stored: identity.schema_hash(),
                        generated,
                    });
                }
                let record = rkyv::from_bytes::<StoredHead, rkyv::rancor::Error>(bytes)
                    .map_err(|_| RecordFamilyError::RecordDecode {
                        family: sema_engine::FamilyName::new("HeadFamily"),
                    })?;
                Ok(Self::HeadFamily(record))
            }
            "EntryFamily" => {
                let generated = sema_engine::SchemaHash::new(
                    family_identity::ENTRY_FAMILY,
                );
                if identity.schema_hash() != generated {
                    return Err(RecordFamilyError::SchemaHashMismatch {
                        family: sema_engine::FamilyName::new("EntryFamily"),
                        stored: identity.schema_hash(),
                        generated,
                    });
                }
                let record = rkyv::from_bytes::<
                    ReceivedEntry,
                    rkyv::rancor::Error,
                >(bytes)
                    .map_err(|_| RecordFamilyError::RecordDecode {
                        family: sema_engine::FamilyName::new("EntryFamily"),
                    })?;
                Ok(Self::EntryFamily(record))
            }
            "CheckpointFamily" => {
                let generated = sema_engine::SchemaHash::new(
                    family_identity::CHECKPOINT_FAMILY,
                );
                if identity.schema_hash() != generated {
                    return Err(RecordFamilyError::SchemaHashMismatch {
                        family: sema_engine::FamilyName::new("CheckpointFamily"),
                        stored: identity.schema_hash(),
                        generated,
                    });
                }
                let record = rkyv::from_bytes::<
                    StoredCheckpoint,
                    rkyv::rancor::Error,
                >(bytes)
                    .map_err(|_| RecordFamilyError::RecordDecode {
                        family: sema_engine::FamilyName::new("CheckpointFamily"),
                    })?;
                Ok(Self::CheckpointFamily(record))
            }
            "RetentionFamily" => {
                let generated = sema_engine::SchemaHash::new(
                    family_identity::RETENTION_FAMILY,
                );
                if identity.schema_hash() != generated {
                    return Err(RecordFamilyError::SchemaHashMismatch {
                        family: sema_engine::FamilyName::new("RetentionFamily"),
                        stored: identity.schema_hash(),
                        generated,
                    });
                }
                let record = rkyv::from_bytes::<
                    RetentionSetting,
                    rkyv::rancor::Error,
                >(bytes)
                    .map_err(|_| RecordFamilyError::RecordDecode {
                        family: sema_engine::FamilyName::new("RetentionFamily"),
                    })?;
                Ok(Self::RetentionFamily(record))
            }
            "PolicyFamily" => {
                let generated = sema_engine::SchemaHash::new(
                    family_identity::POLICY_FAMILY,
                );
                if identity.schema_hash() != generated {
                    return Err(RecordFamilyError::SchemaHashMismatch {
                        family: sema_engine::FamilyName::new("PolicyFamily"),
                        stored: identity.schema_hash(),
                        generated,
                    });
                }
                let record = rkyv::from_bytes::<StorePolicy, rkyv::rancor::Error>(bytes)
                    .map_err(|_| RecordFamilyError::RecordDecode {
                        family: sema_engine::FamilyName::new("PolicyFamily"),
                    })?;
                Ok(Self::PolicyFamily(record))
            }
            _ => {
                Err(RecordFamilyError::UnknownFamily {
                    family: identity.family().clone(),
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteInputRoute {
    PersistSuffix,
    PersistCheckpoint,
    RegisterStore,
    RetireStore,
    PersistRetention,
}

#[rustfmt::skip]
impl WriteInput {
    pub fn route(&self) -> WriteInputRoute {
        match self {
            Self::PersistSuffix(_) => WriteInputRoute::PersistSuffix,
            Self::PersistCheckpoint(_) => WriteInputRoute::PersistCheckpoint,
            Self::RegisterStore(_) => WriteInputRoute::RegisterStore,
            Self::RetireStore(_) => WriteInputRoute::RetireStore,
            Self::PersistRetention(_) => WriteInputRoute::PersistRetention,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadInputRoute {
    CheckAppend,
    CheckCheckpoint,
    CheckObjectNotice,
    LoadRestore,
    LoadHeads,
    LoadRegistry,
}

#[rustfmt::skip]
impl ReadInput {
    pub fn route(&self) -> ReadInputRoute {
        match self {
            Self::CheckAppend(_) => ReadInputRoute::CheckAppend,
            Self::CheckCheckpoint(_) => ReadInputRoute::CheckCheckpoint,
            Self::CheckObjectNotice(_) => ReadInputRoute::CheckObjectNotice,
            Self::LoadRestore(_) => ReadInputRoute::LoadRestore,
            Self::LoadHeads(_) => ReadInputRoute::LoadHeads,
            Self::LoadRegistry(_) => ReadInputRoute::LoadRegistry,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteOutputRoute {
    SuffixPersisted,
    CheckpointPersisted,
    StoreRegistered,
    StoreRetired,
    RetentionPersisted,
    WriteFaulted,
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn route(&self) -> WriteOutputRoute {
        match self {
            Self::SuffixPersisted(_) => WriteOutputRoute::SuffixPersisted,
            Self::CheckpointPersisted(_) => WriteOutputRoute::CheckpointPersisted,
            Self::StoreRegistered(_) => WriteOutputRoute::StoreRegistered,
            Self::StoreRetired(_) => WriteOutputRoute::StoreRetired,
            Self::RetentionPersisted(_) => WriteOutputRoute::RetentionPersisted,
            Self::WriteFaulted(_) => WriteOutputRoute::WriteFaulted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadOutputRoute {
    AppendChecked,
    CheckpointChecked,
    ObjectNoticeChecked,
    RestoreLoaded,
    RestoreRefused,
    HeadsLoaded,
    RegistryLoaded,
    ReadFaulted,
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn route(&self) -> ReadOutputRoute {
        match self {
            Self::AppendChecked(_) => ReadOutputRoute::AppendChecked,
            Self::CheckpointChecked(_) => ReadOutputRoute::CheckpointChecked,
            Self::ObjectNoticeChecked(_) => ReadOutputRoute::ObjectNoticeChecked,
            Self::RestoreLoaded(_) => ReadOutputRoute::RestoreLoaded,
            Self::RestoreRefused(_) => ReadOutputRoute::RestoreRefused,
            Self::HeadsLoaded(_) => ReadOutputRoute::HeadsLoaded,
            Self::RegistryLoaded(_) => ReadOutputRoute::RegistryLoaded,
            Self::ReadFaulted(_) => ReadOutputRoute::ReadFaulted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(WriteInputRoute),
    ReadInput(ReadInputRoute),
    WriteOutput(WriteOutputRoute),
    ReadOutput(ReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    WriteInputRoute::PersistSuffix => "SemaWriteInputPersistSuffix",
                    WriteInputRoute::PersistCheckpoint => {
                        "SemaWriteInputPersistCheckpoint"
                    }
                    WriteInputRoute::RegisterStore => "SemaWriteInputRegisterStore",
                    WriteInputRoute::RetireStore => "SemaWriteInputRetireStore",
                    WriteInputRoute::PersistRetention => "SemaWriteInputPersistRetention",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    ReadInputRoute::CheckAppend => "SemaReadInputCheckAppend",
                    ReadInputRoute::CheckCheckpoint => "SemaReadInputCheckCheckpoint",
                    ReadInputRoute::CheckObjectNotice => "SemaReadInputCheckObjectNotice",
                    ReadInputRoute::LoadRestore => "SemaReadInputLoadRestore",
                    ReadInputRoute::LoadHeads => "SemaReadInputLoadHeads",
                    ReadInputRoute::LoadRegistry => "SemaReadInputLoadRegistry",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    WriteOutputRoute::SuffixPersisted => "SemaWriteOutputSuffixPersisted",
                    WriteOutputRoute::CheckpointPersisted => {
                        "SemaWriteOutputCheckpointPersisted"
                    }
                    WriteOutputRoute::StoreRegistered => "SemaWriteOutputStoreRegistered",
                    WriteOutputRoute::StoreRetired => "SemaWriteOutputStoreRetired",
                    WriteOutputRoute::RetentionPersisted => {
                        "SemaWriteOutputRetentionPersisted"
                    }
                    WriteOutputRoute::WriteFaulted => "SemaWriteOutputWriteFaulted",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    ReadOutputRoute::AppendChecked => "SemaReadOutputAppendChecked",
                    ReadOutputRoute::CheckpointChecked => {
                        "SemaReadOutputCheckpointChecked"
                    }
                    ReadOutputRoute::ObjectNoticeChecked => {
                        "SemaReadOutputObjectNoticeChecked"
                    }
                    ReadOutputRoute::RestoreLoaded => "SemaReadOutputRestoreLoaded",
                    ReadOutputRoute::RestoreRefused => "SemaReadOutputRestoreRefused",
                    ReadOutputRoute::HeadsLoaded => "SemaReadOutputHeadsLoaded",
                    ReadOutputRoute::RegistryLoaded => "SemaReadOutputRegistryLoaded",
                    ReadOutputRoute::ReadFaulted => "SemaReadOutputReadFaulted",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::WriteInput;
    pub type WriteOutput = super::WriteOutput;
    pub type ReadInput = super::ReadInput;
    pub type ReadOutput = super::ReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl WriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for WriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for WriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for ReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for ReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
